### PR TITLE
Focus first item menu open

### PR DESCRIPTION
**Pull request by LeopoldoFu**
For Issue https://github.com/davidtheclark/react-aria-menubutton/issues/51

### CODE REVIEW

**Comment by LeopoldoFu** [comment]
So how exactly do I provide credentials for the tests to run?

**Comment by davidtheclark** [comment]
@LeopoldoFu I think I am going to rewrite this test suite using Jest. I'll just try out this PR manually and see how it goes.

**Comment by davidtheclark** [comment]
@LeopoldoFu I merged this into a v5 branch, because I'd consider this a breaking change. Might take a little while to get that branch out, because the test suite really should be rewritten, as mentioned above. But I will try.

**Comment by davidtheclark** [comment]
@LeopoldoFu Sorry for the back-and-forth —— decided that I do not want to merge this messy history. Can you please cleanup the history, then I'll merge it into v5?

**Comment by davidtheclark** [comment]
@LeopoldoFu: I've rewritten the test suite to use Jest, so that should require some modifications to this PR before we can merge. Still planning to finish this out?

**Comment by LeopoldoFu** [comment]
Yes, although not sure when. Hopefully within two weeks. I've been very busy with finishing up work before a major release at work. Sorry for the delay.

**Comment by davidtheclark** [comment]
@LeopoldoFu I understand. I might find some time to take care of this myself before then. If not, feel free to contribute when you can !

**Comment by vnglst** [comment]
Hi guys!

Came here for the same issue, would be great to have a prop to set the focus on a menu item.

Any way I can help merge this branch?

**Comment by davidtheclark** [comment]
@vnglst, this functionality needs to be tested in Jest. If you'd to champion the feature, I suggest starting a new PR off of master and copying over whatever you like from this one.

Closing this PR due to inactivity.

**Comment by vnglst** [comment]
Great I'll look into it. I need this for a project so I'll first try and get it the work there, but converting the tests in this PR to Jest shouldn't be too much work.

**Pull request closed without merging**
