### PR TITLE
Use React.forwardRef

### LINKED ISSUE #93: Provide `ref` function to access the menu?
Context: I would like to blur the menu when a selection is made, because the design for the focused state of our menu looks very "active".

Is it possible to provide a `ref` function to access the menu's focusable DOM element? I'm not sure if this would be tricky given the implementation of the library or not. Ideally I would be able to just call `.blur()` (or `.focus()`, etc.) on the menu whenever I'd like using a Ref.

Right now, I am doing this by:

```ts
import * as M from 'react-aria-menubutton'

...

    <M.Wrapper
        {...wrapperProps}
        onSelection={(selected: KeyType) => {
          onSelection(selected)

          // Blur the menu after selecting. we don't have a way to
          // get a ref for the menu, so this will have to do
          if (blurOnSelection) {
            // @ts-ignore
            document.activeElement &&
            // @ts-ignore
            document.activeElement.blur &&
            // @ts-ignore
            typeof document.activeElement.blur  === 'function' &&
            // @ts-ignore
            document.activeElement.blur()
          }
        }}
    >
```

### PR DESCRIPTION
**Pull request by nhardy**
Builds on top of the changes in #110, and uses `React.forwardRef` to close #93 and remove `ReactDOM.findDOMNode` (removing `react-dom` from the `peerDependencies`) which closes the remaining issue in #88. Also wraps Demos in `<React.StrictMode />`.

Unfortunately, adding `React.forwardRef` is a backwards-incompatible change and requires the peerDependencies for React to be bumped to `^16.3.0` and will require a major version bump to this library. This version of React was also when the new context API was introduced, so I have removed the dependency on `create-react-context` in favour of just using React's API directly.

### CODE REVIEW

**Comment by shirshendubhowmick** [comment]
@nhardy Just want to make sure that this PR contains all the changes from #110 . In that case we can do major version release with PR

**Comment by nhardy** [comment]
@shirshendubhowmick Yes, it does. Although since this branch requires React >= 16.3 for `React.forwardRef`, it removes `create-react-context` since the new context API was also introduced then.

**Comment by shirshendubhowmick** [comment]
Thanks for the update, planning a release this week.

**Comment by shirshendubhowmick** [comment]
@nhardy #110 is now published under `v6.3.0`. Need some more time to review this as this has some backward incompatible changes. Thanks for your patience.

**Comment by nhardy** [comment]
@shirshendubhowmick Is there anything else I can help with as part of this PR?

**Comment by nhardy** [comment]
@shirshendubhowmick Are these changes going to be published under `v7.0.0`?

**Comment by shirshendubhowmick** [comment]
Yes, expected to be released by by 20th or 21st of this month

**Pull request merged**
