### PR TITLE
fix anchor tag behaviour on keydown

### PR DESCRIPTION
**Pull request by yogaboll**
Addresses issue #74

### CODE REVIEW

**Comment by yogaboll** [comment]
I'm confused as to why the tests are failing on travis. They are passing on my machine.

**Comment by joshsalverda** [comment]
@yogaboll The failures look to be related to the stored snapshots, so I'm pretty sure u need to also update and commit the new snapshots: `jest --updateSnapshot` (source: https://facebook.github.io/jest/docs/en/snapshot-testing.html)

This failure looks a bit suspect, though I'm not familiar enough with the code/tests to know if it's a valid issue: 
screen shot 2017-12-06 at 3 49 42 pm

I'd really like this feature implemented as I'm now running into this issue as well :)

**Comment by joshsalverda** [comment]
Should onSelection also be made optional in this case as well? It's kind of awkward having to define a noop function just to remove the ```The prop `onSelection` is marked as required in `AriaMenuButtonWrapper`, but its value is `undefined`.``` error

**Comment by yogaboll** [comment]
@joshsalverda The snapshot tests are all passing on my computer so --updateSnapshot doesn't change anything. After looking at the specific test that you mention, it seems like it shouldn't be able to fail from only making changes to the MenuItem.js file, since the test only concerns the Menu.js file though I could be wrong on that.

Could this maybe be a problem with different versions of node or jest in the different travis builds?

Good point about the onSelection prop. A possible concern would be that it is a slight regression in the dev experience of people who use this library for the most common use case where onSelection is needed (because they wouldn't receive the proptypes warning).

**Comment by joshsalverda** [comment]
I got around to running these tests locally and they are also failing for me... I noticed the first two failures are "valid", since there is actually a very minor difference between the two... tabIndex vs tabindex

I was able to update the snapshots as well. As you said, it could very well be a version issue... I'm running node v5.3.0 (wow, im really behind...) and jest v21.2.1

**Comment by joshsalverda** [comment]
Also it looks like the pipeline is using node v6, if I'm interpreting this correctly: https://travis-ci.org/davidtheclark/react-aria-menubutton/jobs/311299041/config

**Comment by yogaboll** [comment]
@joshsalverda All tests still pass on my machine when using node 6.12.2 (running on Linux mint 18.2). Very peculiar. Also I think it's time for you to upgrade node :smiley:.

@davidtheclark [Another recent pull request](https://github.com/davidtheclark/react-aria-menubutton/pull/78) which only changed the README caused the tests to fail in the exact same way as my pull request. This causes me to believe that this is definitely not a problem with my changes, but with the existing code and travis. 
Can we get this fixed? And do you think onSelection should be made into an optional prop instead of required? I can change the pr if you think it's best to make it optional.

**Comment by davidtheclark** [comment]
I suspect that Travis started downloading a more recent version of React, or something, that changed the snapshots. I updated `.travis.yml` to get the latest npm, which should respect `package-lock.json` so hopefully avoid this problem. Sorry for the confusion.

So could you please try rebasing onto master, check tests locally, and push to see if Travis works?

I'm ok with making `onSelection` optional, if you think it's a good idea 👍

**Comment by yogaboll** [comment]
Travis now gives us a brand new error related to `npm cache clean`.

**Comment by davidtheclark** [comment]
@yogaboll Oops. Remove the cache cleaning from `.travis.yml`.

**Comment by davidtheclark** [comment]
@yogaboll Thanks again. Published in 5.1.1

**Comment by yogaboll** [comment]
:+1:

**Pull request merged**
