### PR TITLE
Moved role props to defaultProps

### PR DESCRIPTION
**Pull request by Nic128**
I realized I could use this menu component to build a select, or a combobox. The only thing needed is to change the role attributes as needed.

### CODE REVIEW

**Comment by davidtheclark** [comment]
> I realized I could use this menu component to build a select, or a combobox

Are these in compliance with the ARIA spec? If so, we should advertise that! How about code to add to the README showing how this can be done?

**Comment by Nic128** [comment]
According to the ARIA spec, I am missing a detail for building a select. The focus index needs to start at the selected index, not 0.

There's some work to be done in this PR.

**Comment by gouegd** [comment]
I'm also using this as an alternative to <select>.
Nicely done @davidtheclark, this is a good base to build on for slightly different use-cases :)

**Comment by davidtheclark** [comment]
Closing due to lack of activity. Please re-open if you'd like to resume.

**Pull request closed without merging**
