### PR TITLE
Add TypeScript definition files

### PR DESCRIPTION
**Pull request by forabi**
This PR provides types for use with TS projects. It is also useful for vanilla JS projects as it provides autocompletion in VS Code.

screenshot_20170416_144750

### CODE REVIEW

**Comment by davidtheclark** [comment]
@forabi: I understand the impulse here, but I'm not sure I want to merge this PR, because I don't personally want to maintain a definition file for Typescript, which I don't use. Is there an equivalent to flow-typed where you can put this, then add a note to the readme here?

**Comment by forabi** [comment]
@davidtheclark Yes, there is DefinitelyTyped but it is always better to have the types bundled with the package so users do not have to installed a separate definition file. I understand that this requires maintenance and updates with every API change so I will submit a PR to DefinitelyTyped.

P.S. Thanks for this awesome library and thanks for taking a11y seriously! :tada:

**Comment by crohlfs** [comment]
Hi there @forabi I've put together a branch with your type definition ready to create a PR if that sounds good with you at https://github.com/crohlfs/DefinitelyTyped/tree/react-aria-menubutton/types/react-aria-menubutton. Let me know if you want me to go ahead or if you would rather do it.

**Comment by forabi** [comment]
@crohlfs It looks good to me. Thanks for taking the time to contribute to DT!

**Pull request closed without merging**
