### PR TITLE
Make it possible to add an object to value

### PR DESCRIPTION
**Pull request by asundlihardig**
In our menu we want some of the buttons to eighter navigate to internal or external url's. We pass the url to the MenuItem using the value property, so onSelection can trigger the navigation. The problem is that we use React Router which requires us to either call Router.transitionTo() or window.location depending on if the URL is internal or external. We cant t determine if an url is an internal since the value is just a string. If the value could be an object, we could send { internal:true, url:'http://url' }

### CODE REVIEW

**Comment by davidtheclark** [comment]
Thanks! This is a good idea and a simple change. I will release 1.1.0 soon with this change in place.

**Comment by kapilpipaliya** [comment]
when will this released?

**Comment by davidtheclark** [comment]
@kapilpipaliya Was released a while ago: https://github.com/davidtheclark/react-aria-menubutton/blob/master/CHANGELOG.md#110

**Comment by kapilpipaliya** [comment]
thanks a lot.
I read the documenation: 
https://github.com/davidtheclark/react-aria-menubutton#menuitem
If the MenuItem has a value prop, that is passed.

**Pull request merged**
