### PR TITLE
Detect active element in relative document

### PR DESCRIPTION
**Pull request by dundalek**
We are using menubutton rendered in [react-frame-component](https://github.com/ryanseddon/react-frame-component). Referencing global `document` trips off the blur detection and item selection does not work. This PR fixes that by using relative `ownerDocument` reference which works in all cases.

### CODE REVIEW

**Comment by davidtheclark** [comment]
@dundalek Interesting! Glad to learn about this. I will merge and release at some point soonish, hopefully. I'd kind of like to rewrite the test suite but having trouble finding the time ...

**Comment by davidtheclark** [comment]
Merged in 3e1c1ae8edd04f774e279ac387b755afb2eaa15d.

**Comment by davidtheclark** [comment]
@dundalek Do we also need to switch the references to `document` in `Menu.js`? Not sure if I should release this yet ...

**Comment by dundalek** [comment]
For our use case we don't need to handle tap events so we are fine without it. But it might not hurt to change in there also.

**Comment by davidtheclark** [comment]
Published in 4.2.0

**Comment by dundalek** [comment]
Cool, thank you!

**Comment by dundalek** [comment]
Cool, thank you!

**Pull request closed without merging**
